version: '3'

name: movie-theatre

services:

  movies-db:
    image: postgres:16
    env_file:
      - ./.env
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - movies-database:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

  elasticsearch:
    image: elasticsearch:8.6.2
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      # volumes:
      #   - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always

  etl:
    build: ./postgres_to_es
    # command: python main.py
    # volumes:
    #   - static-theatre:/opt/app/static
    # expose:
    #   - "5000"
    env_file:
      - ./postgres_to_es/.env
    # environment:
    #   SQL_HOST: movies-db
    #   ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - movies-db
    # restart: always

volumes:
  movies-database:
    # esdata:

