# version: '3'

name: movie-theater # to change

services:
  movies-db:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - movies-database:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.6.2
    # env_file:
    #   - ./.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      # volumes:
      #   - es-database:/var/lib/postgresql/data
    ports:
      - "9200:9200"

volumes:
  movies-database:
    # static-theatre:
    # service:
    #   build: ./app
    #   volumes:
    #     - static-theatre:/opt/app/static
    #   expose:
    #     - "8000"
    #   env_file:
    #     - ./.env
    #   depends_on:
    #     - theatre-db

    # nginx:
    #   image: nginx:latest
    #   volumes:
    #     - static-theatre:/opt/app/static
    #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #     - ./configs:/etc/nginx/conf.d:ro
    #   depends_on:
    #     - service
    #   ports:
    #     - "80:80"
